project:
  name: cockroachdb-jdbc-wrapper
  version: 0.1.0
  description: A lightweight JDBC wrapper with retries for CockroachDB
  authors:
    - Virag Tripathi
  license: MIT
  java:
    groupId: com.cockroachdb
    artifactId: cockroachdb-jdbc-wrapper
    version: 0.1.0

release:
  github:
    owner: viragtripathi
    name: cockroachdb-jdbc-wrapper
    tagName: v{{projectVersion}}
    releaseName: CockroachDB JDBC Wrapper v{{projectVersion}}
    overwrite: true
    skipTag: false
    changelog:
      enabled: true
      preset: conventional-commits

distributions:
  wrapper:
    type: JAVA_BINARY
    executable:
      name: cockroachdb-jdbc-wrapper
    artifacts:
      - path: target/cockroachdb-jdbc-wrapper-{{projectVersion}}.jar
        platform: slim
        extraProperties:
          classifier: slim
          description: "slim, requires dependencies i.e. Resilience4j & PostgreSQL JAR's"
      - path: target/cockroachdb-jdbc-wrapper-{{projectVersion}}-all.jar
        platform: all
        extraProperties:
          classifier: uber
          description: "Self-contained shaded JAR with Resilience4j included. Only needs PostgreSQL JAR at runtime."

packagers:
  github:
    enabled: true

