name: Java CI with CockroachDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Start CockroachDB container
        run: |
          docker run -d \
            --name crdb \
            -p 26257:26257 \
            cockroachdb/cockroach:latest start-single-node --insecure

      - name: Build and Test
        run: ./mvnw clean verify

  release:
    runs-on: ubuntu-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Install JReleaser
        uses: jreleaser/release-action@v2

      - name: Full Release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw clean package
          jreleaser full-release

