name: Release with JReleaser

on:
  push:
    tags:
      - '*'  # Trigger on any Git tag
  workflow_dispatch:  # Allow manual release trigger

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build Maven Project
        run: ./mvnw clean package -DskipTests

      - name: Set up JReleaser
        uses: jreleaser/release-action@v2

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
          distribution-type: CLI  # Required for jreleaser-cli.jar pathing
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_DEBUG: true
          JRELEASER_TRACE: true
          JRELEASER_VERBOSE: true
