name: Release with JReleaser

on:
  push:
    tags:
      - '*'  # Trigger on any tag
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build Project (skip tests)
        run: ./mvnw clean package -DskipTests

      - name: Install JReleaser CLI
        run: |
          curl -sL https://github.com/jreleaser/jreleaser/releases/download/v1.18.0/jreleaser-cli-1.18.0.zip -o jreleaser.zip
          unzip jreleaser.zip -d jreleaser-cli
          chmod +x jreleaser-cli/bin/jreleaser

      - name: Run JReleaser with config
        run: ./jreleaser-cli/bin/jreleaser full-release --config-file=.jreleaser/config.yml
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
